version: "3.7"

services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "6603:3306"
    environment:
      MYSQL_DATABASE: "correos"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: ""