#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# inicio:
#  path: /
#  controller: App\Controller\RegistroUsuarioController::registro

contacto:
  path: /
  controller: App\Controller\ContactoController::index

contacto.post:
  path: /contacto
  controller: App\Controller\ContactoController::CreateComment

contacto.post.email:
  path: /contacto_email/{commentId}
  controller: App\Controller\ContactoController::SendMailByCommentId
  methods: GET

admin:
  path: /admin
  controller: App\Controller\Admin\DashboardController::index